# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: BuildMS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: softprops/action-gh-release@v1
    - name: Build Solution
    tag_name:
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_verbose.cmd
env:
GITHUB_TOKEN: ${{ secrets.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 }}
