# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: BuildMS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: softprops/action-gh-release@v1
    - name: Build Solution
    tag_name: build1
      shell: cmd
      working-directory: ${{github.workspace}}
      run: build\build_verbose.cmd
